apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quinoa-wind-turbine-nmtn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quinoa-wind-turbine-nmtn
    app.kubernetes.io/part-of: quinoa-wind-turbine
  name: quinoa-wind-turbine-nmtn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quinoa-wind-turbine-nmtn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quinoa-wind-turbine-nmtn
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bsutter-tenant/quinoa-wind-turbine/quinoa-wind-turbine-nmtn@sha256:03e6ae55514a3d058c0a30d4c5dcdafb1a19d0a6f8db2dfae7c85596acd19053
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 250Mi
status: {}
