apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quinoa-wind-turbine-nmtn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quinoa-wind-turbine-nmtn
    app.kubernetes.io/part-of: quinoa-wind-turbine
  name: quinoa-wind-turbine-nmtn
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: quinoa-wind-turbine-nmtn
status:
  loadBalancer: {}
