apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: quinoa-wind-turbine-nmtn
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bsutter-tenant/quinoa-wind-turbine/quinoa-wind-turbine-nmtn@sha256:b44e8f510adb49c1eb65553d22212cfdca30fc64e2dc79c5cf7c7d7ae09d5b35
        name: my-java-quarkus
        resources: {}
status: {}
